#!/bin/bash

bspc monitor HDMI1 -d 1 2 3 4 5 6 7 8 9
bspc monitor LVDS1 -d 0

bsp-layout set tall 1
bsp-layout set tall 2
bsp-layout set tall 3
bsp-layout set tall 4
bsp-layout set tall 5
bsp-layout set tall 6
bsp-layout set tall 7
bsp-layout set tall 8
bsp-layout set tall 9

bspc config border_width                  1
bspc config window_gap                    20
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.60
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#### BSPWM coloring ####
bspc config normal_border_color		"#313244"
#bspc config active_border_color		""
bspc config focused_border_color	"#f1fa8c"
#bspc config presel_feedback_color	""
bspc config urgent_border_color		"#ff5555"

$HOME/.config/bspwm-autostart.sh &
